// HAM10000-adapted mock data for RareSight

export const CASES = [
  {
    id: 'DX-10821',
    name: 'Helen Carter',
    age: 67,
    sex: 'F',
    risk: 'high',
    confidence: 0.94,
    primary: 'Melanoma',
    icd: 'C43.9',
    summary: 'Highly suspicious dermoscopic features consistent with superficial spreading melanoma. Asymmetric pigmentation, irregular border, multicomponent pattern.',
    modality: 'Dermoscopy',
    submitted: '2 hours ago',
    referred: 'Dermatology — urgent',
  },
  {
    id: 'DX-10834',
    name: 'James Whitfield',
    age: 54,
    sex: 'M',
    risk: 'high',
    confidence: 0.89,
    primary: 'Basal Cell Carcinoma',
    icd: 'C44.91',
    summary: 'Pearlescent nodule with central ulceration and arborizing vessels on dermoscopy. Consistent with nodular BCC. Excision recommended.',
    modality: 'Dermoscopy',
    submitted: '5 hours ago',
    referred: 'Dermatology',
  },
  {
    id: 'DX-10847',
    name: 'Patricia Nguyen',
    age: 48,
    sex: 'F',
    risk: 'observation',
    confidence: 0.82,
    primary: 'Actinic Keratoses',
    icd: 'L57.0',
    summary: 'Scaly, erythematous patch on sun-exposed skin. Dermoscopy shows strawberry pattern. Precancerous — treatment with cryotherapy or topical 5-FU advised.',
    modality: 'Dermoscopy',
    submitted: '8 hours ago',
    referred: null,
  },
  {
    id: 'DX-10852',
    name: 'Robert Kim',
    age: 35,
    sex: 'M',
    risk: 'normal',
    confidence: 0.97,
    primary: 'Melanocytic Nevi',
    icd: 'D22.9',
    summary: 'Symmetric, evenly pigmented melanocytic nevus. Dermoscopy shows regular reticular pattern with no atypical features. Routine review recommended.',
    modality: 'Dermoscopy',
    submitted: 'Yesterday',
    referred: null,
  },
];

export const KPIS = [
  { label: "Today's Scans", value: '24', sub: 'Compared to yesterday', trend: '+12%', trendKind: 'up' },
  { label: 'Pending Review', value: '8', sub: 'Awaiting your confirmation', trend: 'Urgent: 2', trendKind: 'urgent' },
  { label: 'Avg. Confidence', value: '94.2%', sub: 'Across all AI diagnostics', trend: 'Calibrated', trendKind: 'badge' },
];

export const LIBRARY_KPIS = [
  { label: 'Documented Cases', value: '12,470', trend: '+8%' },
  { label: 'Training Samples', value: '10,015', trend: '+3.2%' },
  { label: 'Active Researchers', value: '218', trend: '+14' },
];

export const DISEASES = [
  {
    name: 'Melanoma',
    code: 'C43.9',
    category: 'Malignant',
    cases: '4,821',
    summary: 'Malignant neoplasm of melanocytes. Highly variable appearance; dermoscopy essential. Early detection critical for prognosis.',
    modality: 'Dermoscopy',
    riskFactors: 'UV exposure, fair skin, family history, numerous nevi',
    ageGroup: 'Onset 30–60 yrs',
    prevalence: '1:65 lifetime risk',
  },
  {
    name: 'Basal Cell Carcinoma',
    code: 'C44.91',
    category: 'Malignant',
    cases: '3,104',
    summary: 'Most common skin malignancy. Slow-growing; rarely metastasizes. Presents as pearlescent nodule with telangiectasia.',
    modality: 'Dermoscopy',
    riskFactors: 'Cumulative UV exposure, fair skin, immunosuppression',
    ageGroup: 'Onset 40–70 yrs',
    prevalence: '1:5 lifetime risk (high-risk populations)',
  },
  {
    name: 'Actinic Keratoses',
    code: 'L57.0',
    category: 'Precancerous',
    cases: '2,890',
    summary: 'Scaly, rough patches on sun-damaged skin. Precursor to squamous cell carcinoma; treatment reduces malignant transformation risk.',
    modality: 'Dermoscopy',
    riskFactors: 'Chronic UV exposure, outdoor occupation, fair skin',
    ageGroup: 'Onset 40–80 yrs',
    prevalence: '1:10 in high-sun populations',
  },
  {
    name: 'Benign Keratosis-like Lesions',
    code: 'L82.1',
    category: 'Benign',
    cases: '1,654',
    summary: 'Seborrhoeic keratoses and solar lentigo. Benign epidermal proliferations with characteristic "stuck-on" appearance and waxy surface.',
    modality: 'Dermoscopy',
    riskFactors: 'Age, sun exposure, genetic predisposition',
    ageGroup: 'Onset 50+ yrs',
    prevalence: 'Very common; >90% of adults >65',
  },
  {
    name: 'Dermatofibroma',
    code: 'L98.0',
    category: 'Benign',
    cases: '892',
    summary: 'Benign fibrous nodule, typically on lower limbs. Dimple sign on lateral compression. No treatment required unless symptomatic.',
    modality: 'Dermoscopy',
    riskFactors: 'Minor trauma, insect bites; young adults more common',
    ageGroup: 'Any age; peak 20–40 yrs',
    prevalence: 'Common; incidence 1:100',
  },
  {
    name: 'Melanocytic Nevi',
    code: 'D22.9',
    category: 'Benign',
    cases: '3,210',
    summary: 'Common benign melanocytic proliferations. Dermoscopy shows regular reticular or globular patterns. Monitor for atypical changes using ABCDE criteria.',
    modality: 'Dermoscopy',
    riskFactors: 'Genetic factors, UV exposure, fair skin',
    ageGroup: 'Any age',
    prevalence: '1:1 (universal)',
  },
  {
    name: 'Vascular Lesions',
    code: 'D18.01',
    category: 'Benign',
    cases: '654',
    summary: 'Haemangiomas, angiokeratomas, and pyogenic granuloma. Vascular lacunae or red-purple homogeneous pattern on dermoscopy. Usually benign.',
    modality: 'Dermoscopy',
    riskFactors: 'Trauma, hormonal factors, age',
    ageGroup: 'Any age',
    prevalence: '1:100 (varies by subtype)',
  },
];

export const ACTIVITY = [
  { time: '09:42', action: 'New scan uploaded', meta: 'DX-10821 · Helen Carter', kind: 'upload' },
  { time: '09:38', action: 'Diagnosis confirmed', meta: 'DX-10834 · James Whitfield', kind: 'confirm' },
  { time: '08:51', action: 'Referral sent', meta: 'DX-10821 → Dermatology', kind: 'refer' },
  { time: '08:12', action: 'Case archived', meta: 'DX-10852 · Robert Kim', kind: 'archive' },
  { time: 'Yesterday', action: 'Model recalibrated', meta: 'RareSight v2.4.1 deployed', kind: 'system' },
];

export const SAMPLE_PREDICTIONS = [
  { class_name: 'Melanoma', class_id: 'mel', icd: 'C43.9', confidence: 0.942, probability: 0.942, risk: 'high' },
  { class_name: 'Basal Cell Carcinoma', class_id: 'bcc', icd: 'C44.91', confidence: 0.041, probability: 0.041, risk: 'high' },
  { class_name: 'Actinic Keratoses', class_id: 'akiec', icd: 'L57.0', confidence: 0.012, probability: 0.012, risk: 'medium' },
];

export const ANALYSIS_STEPS = [
  'Preprocessing image...',
  'Encoding visual features (BiomedCLIP)...',
  'Computing multimodal embeddings...',
  'Matching against prototype library...',
  'Generating attention rollout map...',
  'Calibrating confidence (temperature scaling)...',
];

export const PROFILE = {
  name: 'Dr. Aris Mendel',
  title: 'General Practitioner · Rural Dermatology',
  practice: 'Riverside Family Health Clinic',
  email: 'a.mendel@riversidefh.med',
  phone: '+44 7700 900 142',
  location: 'Coventry, United Kingdom',
  license: 'GMC-7142839',
  joined: 'March 2023',
  scans: 1842,
  confirmed: 1758,
  referrals: 84,
  avgConfidence: 0.942,
};
